apiVersion: apps/v1
kind: Deployment
metadata:
  name: kafka-consumer
  namespace: default
spec:
  replicas: 1
  selector:
    matchLabels:
      app: kafka-consumer
  template:
    metadata:
      labels:
        app: kafka-consumer
    spec:
      containers:
        - name: kafka-consumer
          image: juanpabloinformatica/consumer_ftd:dev
          imagePullPolicy: Always
          env:
          - name: BOOSTRAP_SERVER
            valueFrom:
              configMapKeyRef:
                name: trade-mirror-configmap
                key: BOOSTRAP_SERVER
          - name: REDIS_HOST
            valueFrom:
              configMapKeyRef:
                name: trade-mirror-configmap
                key: REDIS_HOST
          - name: REDIS_PORT
            valueFrom:
              configMapKeyRef:
                name: trade-mirror-configmap
                key: REDIS_PORT
          - name: TOPIC_FREQUENT_TRADERS
            valueFrom:
              configMapKeyRef:
                name: trade-mirror-configmap
                key: TOPIC_FREQUENT_TRADERS 


