apiVersion: apps/v1
kind: Deployment
metadata:
  name: frontend-deployment
  labels:
    app: frontend
spec:
  selector:
    matchLabels:
      app: frontend
  template:
    metadata:
      labels:
        app: frontend
    spec:
      containers:
      - name: frontend
        image: necs01/trade-mirror:frontend
        ports:
        - containerPort: 4500
        env:
        - name: VITE_API_URL
          valueFrom:
            configMapKeyRef:
              name: trade-mirror-configmap
              key: VITE_API_URL
