apiVersion: apps/v1
kind: Deployment
metadata:
  name: scoring-deployment
  namespace: default
spec:
  replicas: 1
  selector:
    matchLabels:
      app: scoring 
  template:
    metadata:
      labels:
        app: scoring
    spec:
      containers:
        - name: scoring
          image: juanpabloinformatica/scoring:dev
          imagePullPolicy: Always
          env:
          # - name: BOOSTRAP_SERVER
          #   valueFrom:
          #     configMapKeyRef:
          #       name: trade-mirror-configmap
          #       key: BOOSTRAP_SERVER
          - name: REDIS_HOST
            valueFrom:
              configMapKeyRef:
                name: trade-mirror-configmap
                key: REDIS_HOST
          - name: REDIS_PORT
            valueFrom:
              configMapKeyRef:
                name: trade-mirror-configmap
                key: REDIS_PORT

