version: "3"
services:
  database-driver:
    image: database-driver
    build:
      context: database-driver
      dockerfile: ../python.Dockerfile
    network_mode: host
  ftd:
    image: frequent-traders-detector
    build:
      context: ftd
      dockerfile: ../python.Dockerfile
    network_mode: host
  redis:
    image: redis
    container_name: redis-container
    network_mode: host
  rediscommander:
    image: rediscommander/redis-commander
    container_name: redis_commander_container
    restart: always
    environment:
      - REDIS_HOSTS=local:localhost:6379
    network_mode: host
    # ports:
    #   - 8081:8081
