FROM python:3.12-slim-bookworm

RUN apt-get update && apt-get upgrade -y

WORKDIR /app
COPY ./frequent_traders_detection/requirements.txt /app
RUN pip install --no-cache-dir --requirement /app/requirements.txt
COPY ./frequent_traders_detection/ /app
CMD ["python3","producer.py"]
# EXPOSE 8000
# CMD ["uvicorn", "main:app", "--host", "0.0.0.0", "--port", "8000"]
