apiVersion: apps/v1
kind: Deployment
metadata:
  name: front-end
spec:
  replicas: 2
  selector:
    matchLabels:
      app: front-end
  template:
    metadata:
      labels:
        app: front-end
    spec:
      containers:
        - name: frontend
          image: juanpabloinformatica/frontend_crud_rest_api:dev
          imagePullPolicy: Always
          ports:
            - containerPort: 4500
